# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f3k', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utenti',
        ),
    ]
