# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('f3k', '0002_delete_utenti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utenti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cognome', models.CharField(max_length=200)),
                ('Nome', models.CharField(max_length=200)),
            ],
        ),
    ]
